### ISSUE TITLE
Keyboard shortcut?

### ISSUE THREAD

**Issue by aedobbyn** [egnha/gestalt#16]
Thanks for your fantastic presentation of the package at NY Hack R! Now that I've found at least one use for the composer, I have to ask about a keyboard shortcut. I seem to remember you used a one to generate the `%>>>%` -- did you create that via an RStudio Addin or a Mac shortcut or some other method?

**Comment by egnha** [comment]
Thanks for your kind words, I'm glad you enjoyed the presentation! 😊 And good observation: I was indeed using an RStudio keyboard shortcut for `%>>>%`, via a custom [RStudio addin package](https://github.com/egnha/rstudioaddins). (If there is a better way to customize shortcuts in RStudio, I would like to know ... )

**Comment by aedobbyn** [comment]
Nice! I don't know of an easier way to customize shortcuts in RStudio, but this works perfectly. Thanks very much!
