### ISSUE TITLE
Closure formals should agree with those of args()

### ISSUE THREAD

**Issue by egnha** [egnha/gestalt#18]
Replace `rlang::as_closure()`.

**Comment by egnha** [comment]
As of 98076ea69fa5cec2a4b67b23b6c0657ce1f5c1bf, `rlang::as_closure()` breaks `partial()` applied to primitive functions.

**Comment by lionel-** [comment]
Agreed that this might have been a better approach. I've chosen to support both original `args()` and purrr-like `.x` and `.y` for backward compatibility. Also some operators have `NULL` args, like `&&`, so that's not completly general.
