### ISSUE TITLE
Passing an environment as data mask is deprecated

### ISSUE THREAD

**Issue by egnha** [egnha/gestalt#23]
rlang breakage (again):
```
Warning message:
Passing an environment as data mask is deprecated.
Please use `new_data_mask()` to transform your environment to a mask.

  env <- env(foo = "bar")

  # Bad:
  as_data_mask(env)
  eval_tidy(expr, env)

  # Good:
  mask <- new_data_mask(env)
  eval_tidy(expr, mask)
```

**Comment by lionel-** [comment]
`as_data_mask()` is not deprecated, passing an environment is. Allowing environments lead users to bad assumptions about the inheritance chain of their data masks.

**Comment by egnha** [comment]
Right, thanks for the correction! (Somehow, my eyes glazed over the message ... )

**Comment by egnha** [comment]
As of 0.1.6, tests no longer raise this warning.
