### ISSUE TITLE
Compatibility of gestalt with closured primitives in rlang 0.3.1

### ISSUE THREAD

**Issue by lionel-** [egnha/gestalt#24]
Hi Eugene,

I'm preparing a 0.3.1 release for rlang, in https://github.com/r-lib/rlang/tree/rc-0.3.1. It breaks gestalt because of assumptions about the way primitive are closured.

https://github.com/tidyverse/rlang/blob/rc-0.3.1/revdep/problems.md#gestalt

Could you take a look please? I'm planning to send the release in 1 week. Sorry for the short notice.

**Comment by lionel-** [comment]
If you really need to make these assumptions, I suggest duplicating the 0.3.0 code for closuring primitives in your package.

**Comment by egnha** [comment]
Thanks for the heads-up (cf. #18). I'm a bit squeezed for time these days (who isn't?), but I'll see what I can do to get a patch out in sync with rlang 0.3.1.

**Comment by egnha** [comment]
`gestalt::partial("/", 1)(3)` and such now work.
